# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7cc03bf27c1fda46cf3834ae38548e1e28befc0869d9b94c4646a70beb2d94d734ca86b739262882cf6886b5780399fd447fd5ff845b1da9e306eefdb970a6

test:
  secret_key_base: 6fc73f923b52dd55ae8cdce6dffbd40ca86a28f0f3fb6b4537dd0e898009a17399fa1b0882fd963b736434243dab279d34bffe39fec1bb008548b30432357671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
